services:
  postgres:
    image: postgres:16-alpine
    container_name: operis_postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: operis_market
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
